; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=snNucleotide
containsCodingNuc=True
MissingBaseSymbol=?
IdenticalBaseSymbol=.
GapSymbol=-
[ ProcessTypes ]
ppDistEst=true
ppOverallMean=true
[ AnalysisSettings ]
Analysis=Distance Estimation
Scope=Overall Mean
Estimate Variance=====================
Variance Estimation Method=Bootstrap method
No. of Bootstrap Replications=1000
Substitution Model=====================
Substitutions Type=Nucleotide
Model/Method=Tamura 3-parameter model
Fixed Transition/Transversion Ratio=Not Applicable
Substitutions to Include=d: Transitions + Transversions
Rates and Patterns=====================
Rates among Sites=Gamma Distributed (G)
Gamma Parameter=1
Pattern among Lineages=Same (Homogeneous)
Data Subset to Use=====================
Gaps/Missing Data Treatment=Complete deletion
Site Coverage Cutoff (%)=Not Applicable
Select Codon Positions=1st,2nd,3rd,Non-Coding
