; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                = 7170509-x86_64 Mac OS             
[ DataSettings ]
datatype                           = snProtein                         
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
[ ProcessTypes ]
ppDistEst                          = true                              
ppOverallMean                      = true                              
[ AnalysisSettings ]
Analysis                           = Distance Estimation               
Scope                              = Overall Mean                      
Estimate Variance                  = ====================              
Variance Estimation Method         = None                              
No. of Bootstrap Replications      = Not Applicable                    
Substitution Model                 = ====================              
Substitutions Type                 = Amino acid                        
Model/Method                       = Jones-Taylor-Thornton (JTT) model 
Rates and Patterns                 = ====================              
Rates among Sites                  = Gamma Distributed (G)             
Gamma Parameter                    = 1.00                              
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Complete deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
