; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=snNucleotide
containsCodingNuc=True
MissingBaseSymbol=?
IdenticalBaseSymbol=.
GapSymbol=-
[ ProcessTypes ]
ppDistEst=true
ppOverallMean=true
[ AnalysisSettings ]
Analysis=Distance Estimation
Scope=Overall Mean
Estimate Variance=====================
Variance Estimation Method=Bootstrap method
No. of Bootstrap Replications=1000
Substitution Model=====================
Substitutions Type=Syn-Nonsynonymous
Model/Method=Modified Nei-Gojobori method (Jukes-Cantor)
Fixed Transition/Transversion Ratio=2
Substitutions to Include=s: Synonymous only
Rates and Patterns=====================
Rates among Sites=Uniform rates
Gamma Parameter=Not Applicable
Pattern among Lineages=Same (Homogeneous)
Data Subset to Use=====================
Gaps/Missing Data Treatment=Complete deletion
Site Coverage Cutoff (%)=Not Applicable
Select Codon Positions=Not Applicable
Genetic Code=FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG
