; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                      = 0                   
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
[ ProcessTypes ]
ppInfer                                  = true                                    
ppME                                     = true                                    
[ AnalysisSettings ]
Analysis                                 = Phylogeny Reconstruction                
Scope                                    = All Selected Taxa                       
Statistical Method                       = Minimum Evolution method                
Phylogeny Test                           = ====================                    
Test of Phylogeny                        = None                                    
No. of Bootstrap Replications            = Not Applicable                          
Substitution Model                       = ====================                    
Substitutions Type                       = Nucleotide                              
Model/Method                             = No. of differences                      
Fixed Transition/Transversion Ratio      = Not Applicable                          
Substitutions to Include                 = d: Transitions + Transversions          
Rates and Patterns                       = ====================                    
Rates among Sites                        = Uniform Rates                           
Gamma Parameter                          = Not Applicable                          
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Complete deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
Tree Inference Options                   = ====================                    
ME Heuristic Method                      = Close-Neighbor-Interchange (CNI)        
Initial Tree for ME                      = Obtain initial tree by Neighbor-Joining 
ME Search Level                          = 1                                       
Genetic Code Table                       = Not Applicable                          
Genetic Code                             = Not Applicable                          
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
