; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                         = 0                      
[ DataSettings ]
datatype                                    = snNucleotide                               
containsCodingNuc                           = True                                       
MissingBaseSymbol                           = ?                                          
IdenticalBaseSymbol                         = .                                          
GapSymbol                                   = -                                          
[ ProcessTypes ]
ppInfer                                     = true                                       
ppMP                                        = true                                       
[ AnalysisSettings ]
Analysis                                    = Phylogeny Reconstruction                   
Statistical Method                          = Maximum Parsimony                          
Phylogeny Test                              = ====================                       
Test of Phylogeny                           = None                                       
No. of Bootstrap Replications               = Not Applicable                             
Substitution Model                          = ====================                       
Substitutions Type                          = Nucleotide                                 
Data Subset to Use                          = ====================                       
Gaps/Missing Data Treatment                 = Complete deletion                          
Site Coverage Cutoff (%)                    = Not Applicable                             
Select Codon Positions                      = 1st, 2nd, 3rd, Non-Coding                  
Tree Inference Options                      = ====================                       
MP Search Method                            = Subtree-Pruning-Regrafting (SPR)           
No. of Initial Trees (random addition)      = 10                                         
MP Search level                             = 1                                          
Max No. of Trees to Retain                  = 100                                        
Calculate Branch Lengths                    = No                                         
Genetic Code Table                          = Not Applicable                             
Genetic Code                                = Not Applicable                             
Has Time Limit                              = False                                      
Maximum Execution Time                      = -1                                         
