name: Docker Image CI

on:
  push:
    branches:
      - 'docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: xunuopromise
          password: 1e99998b-b09b-4605-8991-b30b9d689d04
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xunuopromise/qap:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
